project:
  type: website
  output-dir: docs
  resources:
    - epdi/imagenes/**
    - epdi/media/**
    - epdi/datos/**

website:
  title: "hsigrist"
  site-url: "https://hsigrist.github.io"
  description: "Materiales docentes y novedades de Formación Diferenciada | Colegio Portaliano"
  repo-url: "https://github.com/hsigrist/hsigrist.github.io"

  navbar:
    title: "hsigrist"
    left:
      - href: novedades/index.qmd
        text: "Novedades"
      - text: "Cursos"
        menu:
          - href: epdi/index.qmd
            text: "EPDI - Estadística"
          - href: ldi/index.qmd
            text: "LDI - Cálculo"
    right:
      - href: about.qmd
        text: "Acerca de"
      - icon: rss
        href: /novedades/index.xml
        aria-label: "Feed RSS de Novedades"
      - icon: github
        href: "https://github.com/hsigrist/hsigrist.github.io"
        aria-label: "GitHub"
      - icon: envelope
        href: "mailto:hsigrist@colegioportaliano.cl"
        aria-label: "Enviar correo"

  page-footer:
    left: "© 2026 Hans Sigrist"

  sidebar:
    - id: sidebar-epdi
      title: "EPDI 2026"
      contents:
        - epdi/index.qmd
        - section: "Presentaciones"
          contents:
            - epdi/presentaciones/presentacion-edpi.qmd
            - epdi/presentaciones/las-lavadoras-previenen-el-embarazo.qmd
        - section: "Programa"
          contents:
            - epdi/programa/index.qmd
        - section: "Evaluación"
          contents:
            - epdi/evaluacion/index.qmd
            - epdi/evaluacion/cuestionario-grupal.qmd
        - section: "Rúbricas"
          contents:
            - epdi/rubricas/index.qmd
            - epdi/rubricas/rubrica-cuestionario-grupal.qmd
        - section: "Lecciones"
          contents:
            - epdi/lecciones/leccion-1-introduccion-a-los-datos.qmd
            - epdi/lecciones/leccion-2-tipos-de-datos.qmd
            - epdi/lecciones/leccion-3-tipos-de-variables.qmd
            - epdi/lecciones/leccion-4-principios-de-muestreo-y-diseño-de-experimentos.qmd
            - epdi/lecciones/leccion-5-experimentos.qmd

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap
    page-layout: full
    respect-user-color-scheme: true
