baseURL: "https://hsigrist.github.io/"
title: Hans Sigrist
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

defaultContentLanguage: es
languages:
  es:
    languageName: "Español"
    weight: 1

menu:
    main:
        - name: Post
          url: post/
          weight: 1
        - name: Artículos
          url: articulos/
          weight: 2
        - name: Libros
          url: libros/
          weight: 3
        - name: Cursos
          url: cursos/
          weight: 4

params:
    description: "Este sitio es un repositorio y blog de material académico del Prof. Hans Sigrist."
    author: Hans Sigrist
    # googleAnalyticsID: "G-XXXXX"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: true
    ShowWordCount: true
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hans Sigrist
          subtitle: "Soy profesor de matemática en enseñanza media en Colegio Portaliano y docente de pregrado en Matemática en Universidad de Playa Ancha, ambos en San Felipe, Chile."
          imageUrl: "hsigrist.png"
          imageWidth: 130
          imageHeight: 130
          buttons:
            - name: Blog
              url: post/
            - name: Artículos
              url: articulos/
            - name: Libros
              url: libros/
            - name: Cursos
              url: cursos/
    socialIcons:
        - name: CV
          url: Hans-Sigrist-Curriculum.pdf
        - name: Email
          url: mailto:hsigrist@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: YouTube
          url: https://www.youtube.com/@ProfHansSigrist
        - name: GitHub
          url: https://github.com/hsigrist

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Hans Sigrist"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true
